"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import Brand from "@/components/Brand";
export default function AppShell({ children, admin = false }: { children: React.ReactNode; admin?: boolean }) {
    const pathname=usePathname(),router=useRouter(); const [open,setOpen]=useState(false);
    const links=admin?[{href:"/admin",label:"Admin Dashboard"},{href:"/admin/audit-logs",label:"Audit Logs"}]:[{href:"/dashboard",label:"Dashboard"},{href:"/dashboard#notes-heading",label:"Notes"}];
    const logout=()=>{localStorage.removeItem("token");router.push("/login");};
    return <div className="min-h-screen bg-[#FFF8F0] text-gray-800 lg:grid lg:grid-cols-[248px_minmax(0,1fr)]"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#EADFD4] bg-white px-4 lg:hidden"><Brand compact /><button type="button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation" className="btn-secondary size-11 px-0"><svg aria-hidden="true" viewBox="0 0 24 24" className="size-5" fill="none" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" d={open?"M6 6l12 12M18 6 6 18":"M4 7h16M4 12h16M4 17h16"} /></svg></button></header><aside className={`${open?"flex":"hidden"} fixed inset-x-0 top-16 z-20 h-[calc(100vh-4rem)] flex-col border-r border-[#EADFD4] bg-white p-5 lg:sticky lg:top-0 lg:flex lg:h-screen`}><div className="hidden lg:block"><Brand /></div><nav aria-label="Primary navigation" className="mt-4 space-y-1 lg:mt-10">{links.map(link=>{const active=link.href.split("#")[0]===pathname;return <Link key={link.href} href={link.href} onClick={()=>setOpen(false)} className={`flex min-h-11 items-center gap-3 rounded-lg px-3 text-sm font-semibold transition ${active?"bg-[#FFF1E6] text-orange-700":"text-gray-600 hover:bg-[#FFF8F0] hover:text-gray-900"}`}><span className={`size-2 rounded-full ${active?"bg-orange-500":"bg-gray-300"}`} />{link.label}</Link>;})}</nav><div className="mt-auto border-t border-[#EADFD4] pt-4"><p className="px-3 text-xs font-medium uppercase tracking-wider text-gray-400">Secure workspace</p><button type="button" onClick={logout} className="mt-2 flex min-h-11 w-full items-center rounded-lg px-3 text-sm font-semibold text-gray-600 transition hover:bg-red-50 hover:text-red-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-300">Log out</button></div></aside><main className="min-w-0 px-4 py-7 sm:px-6 lg:px-8 lg:py-9"><div className="mx-auto max-w-6xl">{children}</div></main></div>;
}
