"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import AuthShell from "@/components/AuthShell";
import { apiRequest } from "@/lib/api";

const getErrorMessage=(error:unknown)=>error instanceof Error?error.message:"Something went wrong";
export default function LoginPage(){
 const router=useRouter(); const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[otp,setOtp]=useState(""),[challengeToken,setChallengeToken]=useState<string|null>(null),[message,setMessage]=useState(""),[isError,setIsError]=useState(false),[isSubmitting,setIsSubmitting]=useState(false),[sessionExpired,setSessionExpired]=useState(false);
 useEffect(()=>{if(new URLSearchParams(window.location.search).get("session")!=="expired")return;const timer=window.setTimeout(()=>{setSessionExpired(true);setIsError(true);setMessage("Your session has expired. Please sign in again.");},0);return()=>window.clearTimeout(timer);},[]);
 const handleLogin=async(e:React.FormEvent)=>{e.preventDefault();setIsSubmitting(true);try{const data=await apiRequest("/auth/login",{method:"POST",body:JSON.stringify({email,password})});if(data.mfaRequired===true&&typeof data.challengeToken==="string"&&data.challengeToken){setChallengeToken(data.challengeToken);setPassword("");setOtp("");setIsError(false);setSessionExpired(false);setMessage("A 6-digit verification code was sent to your email.");return;}if(typeof data.token!=="string"||!data.token)throw new Error("Unable to complete sign in");localStorage.setItem("token",data.token);setIsError(false);setMessage("Login successful");router.push("/dashboard");}catch(error:unknown){setIsError(true);setMessage(getErrorMessage(error));}finally{setIsSubmitting(false);}};
 const handleOtpVerification=async(e:React.FormEvent)=>{e.preventDefault();if(!challengeToken||!/^\d{6}$/.test(otp)){setIsError(true);setMessage("Enter the 6-digit verification code sent to your email.");return;}setIsSubmitting(true);try{const data=await apiRequest("/auth/verify-otp",{method:"POST",body:JSON.stringify({challengeToken,otp})});if(typeof data.token!=="string"||!data.token)throw new Error("Unable to complete verification");localStorage.setItem("token",data.token);setIsError(false);setMessage("Login successful");router.push("/dashboard");}catch{setIsError(true);setMessage("The verification code is invalid or expired. Please sign in again if you need a new code.");}finally{setIsSubmitting(false);}};
 const returnToLogin=()=>{setChallengeToken(null);setOtp("");setMessage("");setIsError(false);};
 return <AuthShell><div className="mb-8"><span className="eyebrow">Private workspace</span><h1 className="mt-3 text-3xl font-bold tracking-tight text-gray-900">{challengeToken?"Verify your identity":"Welcome back"}</h1><p className="mt-3 text-sm leading-6 text-gray-600">{challengeToken?`We sent a 6-digit verification code to ${email}.`:"Enter your credentials to access your secure workspace."}</p></div>{challengeToken?<form onSubmit={handleOtpVerification} className="space-y-5"><div><label htmlFor="otp" className="label">Verification code</label><input id="otp" type="text" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} placeholder="000000" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} className="field text-center text-xl font-semibold tracking-[0.45em]" autoComplete="one-time-code" aria-describedby="otp-help" autoFocus required/><p id="otp-help" className="mt-2 text-xs text-gray-500">Verification codes expire after 5 minutes.</p></div><button type="submit" disabled={isSubmitting||otp.length!==6} className="btn-primary w-full">{isSubmitting?"Verifying...":"Verify and sign in"}</button><button type="button" onClick={returnToLogin} disabled={isSubmitting} className="btn-secondary w-full">Back to sign in</button></form>:<form onSubmit={handleLogin} className="space-y-5"><div><label htmlFor="email" className="label">Email address</label><input id="email" type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} className="field" autoComplete="email" required/></div><div><label htmlFor="password" className="label">Password</label><input id="password" type="password" placeholder="Enter your password" value={password} onChange={e=>setPassword(e.target.value)} className="field" autoComplete="current-password" required/></div><button type="submit" disabled={isSubmitting} className="btn-primary w-full">{isSubmitting?"Signing in...":"Sign in securely"}</button></form>}{message&&<p role={isError?"alert":"status"} className={`mt-5 rounded-xl border px-4 py-3 text-sm leading-6 ${isError?(sessionExpired?"border-amber-200 bg-amber-50 text-amber-800":"border-red-200 bg-red-50 text-red-700"):"border-green-200 bg-green-50 text-green-700"}`}>{message}</p>} {!challengeToken&&<p className="mt-8 border-t border-[#EADFD4] pt-6 text-center text-sm text-gray-500">New to SecureNotes? <Link href="/register" className="font-semibold text-orange-600 hover:text-orange-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-300">Create an account</Link></p>}</AuthShell>;
}
