"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import AppShell from "@/components/AppShell";
import { apiRequest } from "@/lib/api";
interface AuditLog{id:number;action:string;details:string|null;userId:number;createdAt:string}
const formatTimestamp=(timestamp:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"medium"}).format(new Date(timestamp));
const badge=(action:string)=>action==="LOGIN"?"bg-green-50 text-green-700":action==="LOGIN_FAILED"||action==="NOTE_DELETED"?"bg-red-50 text-red-700":action==="NOTE_UPDATED"?"bg-amber-50 text-amber-700":"bg-orange-50 text-orange-700";
export default function AdminAuditLogsPage(){const router=useRouter();const[logs,setLogs]=useState<AuditLog[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{const data=await apiRequest("/audit-logs");setLogs(Array.isArray(data)?data:[]);setError("");}catch(e:unknown){setError(e instanceof Error?e.message:"Unable to load audit logs");}finally{setLoading(false);}},[]);useEffect(()=>{if(!localStorage.getItem("token")){router.replace("/login");return;}const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load,router]);return <AppShell admin><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="eyebrow">Administration</span><h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900">Audit Logs</h1><p className="mt-2 text-sm text-gray-600">Review authentication and security-related activity.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin" className="btn-secondary">Admin dashboard</Link><button type="button" onClick={()=>void load()} disabled={loading} className="btn-primary">Refresh</button></div></header><section className="surface mt-8 overflow-hidden">{loading?<p role="status" className="px-6 py-14 text-center text-sm text-gray-500">Loading audit logs...</p>:error?<div role="alert" className="m-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>:logs.length===0?<p className="px-6 py-14 text-center text-sm text-gray-500">No audit logs found.</p>:<div className="overflow-x-auto"><table className="min-w-[780px] w-full text-left text-sm"><thead className="sticky top-0 bg-[#FFF8F0] text-xs uppercase tracking-wider text-gray-500"><tr><th className="px-6 py-4 font-semibold">Action</th><th className="px-6 py-4 font-semibold">User</th><th className="px-6 py-4 font-semibold">Details</th><th className="px-6 py-4 font-semibold">Date / time</th></tr></thead><tbody className="divide-y divide-[#EADFD4]">{logs.map(log=><tr key={log.id} className="hover:bg-[#FFFCF8]"><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${badge(log.action)}`}>{log.action}</span></td><td className="whitespace-nowrap px-6 py-4 text-gray-700">User #{log.userId}</td><td className="max-w-md px-6 py-4 text-gray-600">{log.details||"—"}</td><td className="whitespace-nowrap px-6 py-4 text-gray-500"><time dateTime={log.createdAt}>{formatTimestamp(log.createdAt)}</time></td></tr>)}</tbody></table></div>}</section></AppShell>;}
